apiVersion: apps/v1
kind: Deployment
metadata:
  name: f20itonktseisgr13ssp
  namespace: itonk-tseis-gr13
  labels:
    app: f20itonktseisgr13ssp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: f20itonktseisgr13ssp
  template:
    metadata:
      labels:
        app: f20itonktseisgr13ssp
    spec:
      containers:
        - image: "docker.io/stanie/ssp:latest"
          imagePullPolicy: Always
          name: f20itonktseisgr13ssp
          resources:
            limits:
              cpu: 200m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
    name: f20itonkservicegr13ssp
    namespace: itonk-tseis-gr13
    labels:
      app: f20itonktseisgr13ssp
spec:
  selector:
    app: f20itonktseisgr13ssp
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 80
  type: LoadBalancer