apiVersion: apps/v1
kind: Deployment
metadata:
  name: f20itonktseisgr13ssr
  namespace: itonk-tseis-gr13
  labels:
    app: f20itonktseisgr13ssr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: f20itonktseisgr13ssr
  template:
    metadata:
      labels:
        app: f20itonktseisgr13ssr
    spec:
      containers:
        - image: "docker.io/stanie/ssr:latest"
          imagePullPolicy: Always
          name: f20itonktseisgr13ssr
          resources:
            limits:
              cpu: 200m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
    name: f20itonkservicegr13ssr  
    labels: 
spec:
  selector:
    app: f20itonktseisgr13ssr
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 80
  type: NodePort