kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: f20itonkingress-grp13
  namespace: itonk-tseis-gr13
  annotations:
    ingress.kubernetes.io/add-base-url: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  rules:
    - host: itonk-tseis-gr13.dk
      http:
        paths:
          # (.*) Gør at der matches på alt hvad der står efter /backend/
          # For mere information https://kubernetes.github.io/ingress-nginx/examples/rewrite/ 
          - path: /backend/(.*)
            backend:
              serviceName: f20itonkingress-grp13
              servicePort: 8080
          - path: /(.*)
            backend:
              serviceName: f20itonkingress-grp13
              servicePort: 8080
status:
  loadBalancer:
    ingress:
      - ip: 34.76.205.89