  
kind: Ingress
apiVersion: networking.k8s.io/v1beta1
metadata:
  name: ingress-g13
  namespace: itonk-tseis-gr13
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  rules:
    - host: itonk-tseis-gr13.dk
      http:
        paths:
          - path: /currentStocks/(.*)
            backend:
              serviceName: psoc-service-gr13
              servicePort: 8080
          - path: /stockTaxing/(.*)
            backend:
              serviceName: ttc-service-gr13
              servicePort: 8081
          - path: /requesters/(.*)
            backend:
              serviceName: ssr-service-gr13
              servicePort: 8082
          - path: /stockProviders/(.*)
            backend:
              serviceName: ssp-service-gr13
              servicePort: 8083
          - path: /transactions/(.*)
            backend:
              serviceName: stb-service-gr13
              servicePort: 8084
status:
  loadBalancer:
    ingress:
      - ip: 34.76.205.89