apiVersion: apps/v1
kind: Deployment
metadata:
  name: f20itonktseisgr13tts
  namespace: itonk-tseis-gr13
  labels:
    app: f20itonktseisgr13tts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: f20itonktseisgr13tts
  template:
    metadata:
      labels:
        app: f20itonktseisgr13tts
    spec:
      containers:
        - image: "docker.io/stanie/tts:latest"
          imagePullPolicy: Always
          name: f20itonktseisgr13tts
          resources:
            limits:
              cpu: 200m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
    name: ttc-service-g13  
    labels: 
spec:
  selector:
    app: f20itonktseisgr13tts
  ports:
    - protocol: TCP
      port: 6973
      targetPort: 80
  type: LoadBalancer